<a href="https://colab.research.google.com/github/sahil301290/Python-for-Data-Science/blob/main/05_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy library is the first data science library which we need to learn and it has helped in building libraries such as scikit-learn, Pandas, Seaborn, etc.

###Agenda

1. Understand NumPy

2. Create arrays with NumPy

  - Transforming lists
  - Using built-in functions
  - Random data generation

3. Retrieve information from NumPy array using slicing and indexing

4. Basic NumPy Operations

5. Indexing and Selection

  - Grabbing single and a slice of elements
  - Broadcasting selections
  - Indexing and selection in 2D
  - Conditional selection

6. Numpy Operations

7. Vectorization

NumPy is a Python library to create N-dimensional arrays.

Broadcasting can be done using NumPy.

It has built-in capabilities for linear algebra, trigonometry, random number generation, and statistical distributions

###Numpy Arrays

Three techniques are available to us for the same:

1. Transforming lists
2. Using built-in functions
3. Random data generation

In [1]:
import numpy as np

In [2]:
A = [1, 2, 3]
print(type(A))
print(A)

<class 'list'>
[1, 2, 3]


In [3]:
Arr_A = np.array(A)
print(type(Arr_A))
print(Arr_A)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
L_o_L = [[1,1,1],[2,2,2],[3,3,3]]
print(L_o_L)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]


In [5]:
np.array(L_o_L)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [6]:
np.arange(0,50,5)   #start, stop, step

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,20,4)   #Returns evenly spaced 4 numbers from 0 to 20 including 20

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [12]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [13]:
np.eye(4)     #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random Distributions

In [14]:
np.random.rand(1)      #[)

array([0.52392159])

In [15]:
np.random.rand(5,6)

array([[0.60674279, 0.7861796 , 0.49881813, 0.22201095, 0.07666932,
        0.48920721],
       [0.35090118, 0.40950255, 0.70112094, 0.42630034, 0.00352198,
        0.56201155],
       [0.79404838, 0.81246396, 0.36931066, 0.43734333, 0.00764353,
        0.01143257],
       [0.17174626, 0.37243219, 0.68241662, 0.57241667, 0.50363962,
        0.48499019],
       [0.83224034, 0.61550596, 0.68313465, 0.1603516 , 0.29213324,
        0.25726765]])

In [16]:
np.random.randn(5)      #standard normal distribution, mean is 0 and variance is 1

array([-1.32069564,  0.48113448, -0.20809592,  0.62505632,  0.7508231 ])

In [17]:
np.random.randn(2,3)

array([[-1.13852124,  0.52957366,  0.86733792],
       [-2.11201418,  0.24923121, -0.01077554]])

In [18]:
np.random.randint(0,10,3)      #Random integers

array([9, 0, 0])

In [19]:
np.random.randint(0,50,(4,5))

array([[37, 29, 28, 15, 35],
       [28,  3, 28, 48, 29],
       [48, 10, 29, 24, 40],
       [44,  2, 26, 49, 16]])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [22]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [23]:
A = np.arange(0, 25)

In [24]:
A.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#A.reshape(5,3)

In [26]:
RandArr = np.random.randint(0,51,8)
RandArr

array([43, 29, 37,  1, 20, 32, 11, 21])

In [27]:
RandArr.max()

43

In [28]:
RandArr.min()

1

In [29]:
RandArr.argmax()

0

In [30]:
RandArr.argmin()

3

In [31]:
RandArr.dtype

dtype('int64')

In [32]:
A.shape

(25,)

In [33]:
A = A.reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
A.shape

(5, 5)

In [35]:
A = A.reshape(1,25)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

###Indexing and Selection

- Grabbing single and a slice of elements
- Broadcasting selections
- Indexing and selection in 2D
- Conditional selection

Grabbing elements

In [36]:
array = np.arange(0,15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
array[4]

4

In [38]:
array[4:9]

array([4, 5, 6, 7, 8])

In [39]:
array[0:4]

array([0, 1, 2, 3])

In [40]:
array[:4]

array([0, 1, 2, 3])

In [41]:
array[9:]

array([ 9, 10, 11, 12, 13, 14])

Broadcasting Selections

In [42]:
array[9:] = 100
array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100, 100, 100, 100,
       100, 100])

In [43]:
array = np.arange(0,15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
slicingarray =array[1:6]
slicingarray

array([1, 2, 3, 4, 5])

In [45]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
slicingarray[:] = 100
slicingarray

array([100, 100, 100, 100, 100])

In [47]:
array

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [48]:
arraycopy = array.copy()
arraycopy

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [49]:
arraycopy[:] = 100
arraycopy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [50]:
array

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

Indexing and Selection in 2D

In [51]:
array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array2D.shape

(3, 3)

In [53]:
array2D[0]

array([1, 2, 3])

In [54]:
array2D[2]

array([7, 8, 9])

In [55]:
print(array2D[1][2])
print(array2D[1,2])

6
6


In [56]:
print(array2D[0,2])

3


In [57]:
array2D[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
array2D[:2,1:]

array([[2, 3],
       [5, 6]])

Conditional Selection

In [59]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
bool_array = array>5
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
array[bool_array]

array([ 6,  7,  8,  9, 10])

In [63]:
array[array>5]

array([ 6,  7,  8,  9, 10])

###NumPy Operations

In [64]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
array - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [67]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
array * array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
array/array

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
#1 / 0

In [73]:
1/array

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [74]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [76]:
np.log(array)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
 array.sum()

45

In [78]:
array.mean()

4.5

In [79]:
array.max()

9

In [80]:
array.var()

8.25

In [81]:
array.std()

2.8722813232690143

In [82]:
array2d = np.arange(0,25).reshape(5,5)
array2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
array2d.shape

(5, 5)

In [84]:
array2d.sum()

300

In [85]:
array2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [86]:
array2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

###Vectorization

####Agenda - Why to minimize usage of loops?

Let's see the difference in time taken for execution of dot product function using a For Loop versus Vectorization in Python. 

Libraries needed for Vectorization: numpy and time

In [87]:
a = np.array([1,2,3,4])     #This is how to declare a 1D array
print(a)
#numpy.random.rand() method creates array of specified shape with random values.
b = np.random.rand(5)       #Generating 5 random values
print(b)

[1 2 3 4]
[0.00706631 0.02306243 0.52477466 0.39986097 0.04666566]


In [88]:
import time

a = np.random.rand(10000000)       #a is 1D array of 10 Million Random Values
b = np.random.rand(10000000)

###Comparing the time taken for dot product of a and b vectors in milliseconds

Background on time.time(): returns the time as a floating point number expressed in seconds since the epoch, in UTC. Literally speaking the epoch is Unix time 0 (midnight 1/1/1970)

In [89]:
tic = time.time()
c   = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized Version:"+str(1000*(toc-tic))+"ms")
c=0
tic = time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For Loop Version:"+str(1000*(toc-tic))+"ms")

2499546.2026826087
Vectorized Version:13.635873794555664ms
2499546.2026828593
For Loop Version:6599.217176437378ms
